---
## Client
# Forwarder
- name: Install forwarder config
  ansible.builtin.template:
    src: forwarder.conf.j2
    dest: /etc/td-agent/config.d/forwarder.conf
    owner: root
    group: root
    mode: 0644
  when: fluentd_forward_messages
  notify: Restart fluentd

# syslog
- name: Install syslog config
  ansible.builtin.template:
    src: syslog.conf.j2
    dest: /etc/td-agent/config.d/syslog.conf
    owner: root
    group: root
    mode: 0644
  register: fluentd_syslog
  notify: Restart fluentd

- name: Configure syslog forwarding
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    line: "*.*          @127.0.0.1:5140"
  when: fluentd_syslog is succeeded
  notify: Restart rsyslog for fluentd
