---
## Server

# ElasticSearch plugin
- name: Install fluentd plugins # noqa no-changed when
  ansible.builtin.command: td-agent-gem install fluent-plugin-cloudwatch-logs
  when: forward_to_cw is defined or forward_to_cw

- name: Configure cloudwatch forwarding
  ansible.builtin.template:
    src: forward_cw.conf.j2
    dest: /etc/td-agent/config.d/forward_cw.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fluentd

# Set receiver
- name: Configure fluentd receiver
  ansible.builtin.copy:
    src: receiver.conf
    dest: /etc/td-agent/config.d/receiver.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fluentd
