---
## Server

# ElasticSearch plugin
- name: install fluentd plugins
  shell: td-agent-gem install fluent-plugin-cloudwatch-logs
  when: forward_to_cw is defined or forward_to_cw

- template: src=forward_cw.conf.j2 dest=/etc/td-agent/config.d/forward_cw.conf owner=root group=root mode=644
  notify: restart fluentd

# Set receiver
- copy: src=receiver.conf dest=/etc/td-agent/config.d/receiver.conf owner=root group=root mode=644
  notify: restart fluentd
