---

- name: Compiling and installing elasticsearch plugin dependencies # noqa no-changed when
  ansible.builtin.command: td-agent-gem install fluent-plugin-elasticsearch

- name: Restart fluentd
  ansible.builtin.service:
    name: td-agent
    state: restarted

- name: Restart rsyslog for fluentd
  ansible.builtin.service:
    name: rsyslog
    state: restarted
